version: '3.8'

services:
  voice-ai-assistant:
    build: .
    ports:
      - "8787:8787"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PORT=8787
      - HTTP_REFERER=http://localhost
      - X_TITLE=Voice AI Assistant
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8787/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s